[workspace]
resolver = "2"
members = [
    "yoshi",         # facade
    "yoshi-std",     # core engine
    "yoshi-derive",  # procedural macros
    "yoshi-benches", # comprehensive benchmarks
]
# Exclude benchmarks from packaging operations
exclude = [
    "yoshi-benches", # benchmarks don't need to be published
]

# -------- Shared build profiles --------
[profile.dev] # fast ≈ release-like debug builds
opt-level = 1           # some inlining & vectorisation
codegen-units = 4       # keep incremental relinking quick
debug = true
debug-assertions = true
overflow-checks = true
incremental = true      # lightning-fast rebuilds
panic = "unwind"

[profile.dev.package."yoshi-std"] # micro-optimise hot crate
opt-level = 2

[profile.release] # production artefacts
opt-level = "z"   # size-optimised but keeps perf high
lto = "thin"
codegen-units = 1 # maximise cross-crate inlining
panic = "abort"
debug = false
strip = "symbols"

# Workspace dependencies for benchmarking
[workspace.dependencies]
criterion = { version = "0.6.0", features = [
    "html_reports",
    "csv_output",
    "cargo_bench_support",
] }
anyhow = "1.0.98"
thiserror = "2.0.12"
rayon = "1.10.0"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
