[package]
name = "yoshi-std"
version = "0.1.4"
edition = "2021"
rust-version = "1.87.0"                                               # MSRV
authors = ["Lord Xyn <LordXyn@proton.me>"]
repository = "https://github.com/arcmoonstudios/yoshi"
license = "MIT OR Apache-2.0"
description = "Core, std-only error type for the Yoshi framework."
keywords = ["error", "error-handling", "yoshi", "std-only", "no-std"]
categories = ["development-tools", "rust-patterns"]

[dependencies]
serde = { version = "1.0.219", optional = true, features = ["derive"] }
serde_json = { version = "1.0.140", optional = true }
tracing = { version = "0.1.41", optional = true }
miette = { version = "7.6.0", optional = true }
tokio = { version = "1.45.1", optional = true, features = ["time"] }

[features]
default = ["std"]
std = []
derive = []                             # pass-through flag
serde = ["dep:serde", "dep:serde_json"]
tracing = ["dep:tracing"]
async = ["dep:tokio"]

# tech-preview toggles (OFF by default)
unstable-metrics = [
    "serde",
] # Add serde to unstable-metrics feature for ProcessError serialization
unstable-auto-fix = []
unstable-smart-diagnostics = []

[lib]
name = "yoshi_std"
path = "src/lib.rs"

# docs.rs specific configuration for nightly compatibility
[package.metadata.docs.rs]
all-features = true
