[package]
name = "yoshi-derive"
version = "0.1.4"
edition = "2021"
rust-version = "1.87.0"                                                 # MSRV
authors = ["Lord Xyn <LordXyn@proton.me>"]
repository = "https://github.com/arcmoonstudios/yoshi"
license = "MIT OR Apache-2.0"
description = "Procedural-macro helpers for deriving Yoshi errors."
keywords = ["proc-macro", "error", "derive", "error-handling", "yoshi"]
categories = ["development-tools", "rust-patterns"]

[dependencies]
darling = "0.20.11"
once_cell = "1.21.3"
proc-macro2 = "1.0.95"
quote = "1.0.40"
regex = "1.11.1"
syn = { version = "2.0.101", features = ["full", "extra-traits", "derive"] }
yoshi-std = { version = "0.1.4", path = "../yoshi-std" }

[lib]
proc-macro = true

# docs.rs specific configuration for robust builds
[package.metadata.docs.rs]
rustc-args = ["--cap-lints=warn"]
features = []                          # proc-macro crate with no features
no-default-features = false
rustdoc-args = ["--cfg", "docsrs"]
targets = ["x86_64-unknown-linux-gnu"]
