[package]
name         = "yoshi"
version      = "0.1.0"
edition      = "2021"
rust-version = "1.87.0"
authors      = ["Lord Xyn <LordXyn@proton.me>"]
repository   = "https://github.com/arcmoonstudios/yoshi"
license-file = "LICENSE"
description  = "Facade for the Yoshi error framework."
keywords     = ["error","error-handling","result","anyhow","thiserror","std-only","facade"]
categories   = ["error-handling","development-tools::debugging"]

[dependencies]
yoshi-std    = { version = "0.1.0", path = "../yoshi-std", default-features = false }
yoshi-derive = { version = "0.1.0", path = "../yoshi-derive", optional = true }

serde   = { version = "1.0.219", optional = true, features = ["derive"] }
tracing = { version = "0.1.41", optional = true }
miette  = { version = "7.6.0", optional = true }


# Enhanced dependencies for Rust 1.87 features
tokio = { version = "1.42.0", optional = true, features = ["full"] }
serde_json = { version = "1.0.133", optional = true }
once_cell = { version = "1.21.3", optional = true }

[features]
default   = ["std", "rust-1-87", "auto-fix", "smart-diagnostics"]
std       = ["yoshi-std/std"]

derive    = ["yoshi-derive", "yoshi-std/derive"]

serde     = ["dep:serde", "dep:serde_json", "yoshi-std/serde"]
tracing   = ["dep:tracing", "yoshi-std/tracing"]

# Enhanced Rust 1.87 features
rust-1-87 = ["dep:once_cell", "simd-optimized", "precise-capturing"]
async     = ["dep:tokio", "rust-1-87"]
simd-optimized = []
precise-capturing = []

# convenience
full = ["std","derive","serde","tracing","rust-1-87","async"]

# pass-through experimental flags
unstable-metrics            = ["yoshi-std/unstable-metrics"]
unstable-auto-fix           = ["yoshi-std/unstable-auto-fix"]
unstable-smart-diagnostics  = ["yoshi-std/unstable-smart-diagnostics"]

# Enhanced feature flags
pipe                        = ["rust-1-87"]
auto-fix                    = ["unstable-auto-fix", "smart-diagnostics"]
smart-diagnostics           = ["unstable-smart-diagnostics", "rust-1-87"]
cli                         = ["std"]
cross-process               = ["pipe", "serde"]
performance-monitoring      = ["rust-1-87"]